import type { Metadata } from "next";
import Providers from "./providers/providers";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import {
  ActionIcon,
  Box,
  Group,
  Image,
  MantineProvider,
  Text,
} from "@mantine/core";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IoMenu } from "react-icons/io5";
import { useDisclosure } from "@mantine/hooks";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider
          theme={{ defaultRadius: "xl", primaryColor: "green" }}
          defaultColorScheme="light"
        >
          <Navbar />
          <Providers>{children}</Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
